### ISSUE TITLE
how to contribute?

### ISSUE THREAD

**Issue by Licenser** [marianoguerra/little-riak-core-book#7]
I have recently working on the resize part of riak_core and would like to document that somewhere. And while a blog post might be fun it seems nicer to contribute to something more lasting like this book ;).

But that said I'm a bit at a loss as of where to start?

**Comment by marianoguerra** [comment]
hi! that's great news, I have yet to add the metadata chapter myself :)

you need to 

* clone this repo
* install sphinx (http://www.sphinx-doc.org/en/stable/) 
* create a file in the source folder (https://github.com/marianoguerra/little-riak-core-book/tree/master/source) 
* add the section to the index (https://github.com/marianoguerra/little-riak-core-book/blob/master/source/index.rst) 

build:

    make html

serve and open in your browser:

    python -m SimpleHTTPServer

or

    python3 -m http.server

open http://localhost:8000

if you are lazy just open a PR with the file on source dir and I will do the build :)

btw, the format is restructured text (http://docutils.sourceforge.net/rst.html)
